### ISSUE TITLE
Where is the document history for the AV best practices?

### ISSUE THREAD

**Issue by envisionit-moyer** [citrix/en-us-tech-zone#1912]
I don't see a Tech Zone document history for updating the Endpoint Security and Antivirus Best Practices; what changed from March 20, 2020, to now?  Can the history be updated for changes?

https://docs.citrix.com/en-us/tech-zone/build/tech-papers/antivirus-best-practices.html

**Comment by martinzugec-ctx** [comment]
Hi @envisionit-moyer, 

We update history only for new content or major updates. We update multiple articles on a daily basis (just preparing update for 3 articles right now), so it's not reasonable to post all changes to our RSS feed (that's what document history is).

However, since we are using Git as a backend system, all changes can be traced. For AV best practices, you can find all changes to markdown here: 
https://github.com/citrix/en-us-tech-zone/commits/master/en-us/tech-zone/build/tech-papers/antivirus-best-practices.md
