### ISSUE TITLE
This Article is Lacking in Details

### ISSUE THREAD

**Issue by ctxcommunity** [citrix/en-us-tech-zone#1919]
https://docs.citrix.com/en-us/tech-zone/learn/tech-insights/authentication-saml.html

For a Technical Article this lacking in technical details.  It's great for a high level overview but that information can be obtained through other avenues.

There is no information on technical requirements, implementation, nuances and limitations.  Admins are going to banging their head against the wall trying to implement this only to find out later that IDP initiated logins are not supported. Only SP initiated by Workspace itself.

Joe

**Comment by martinzugec-ctx** [comment]
I'm sorry Joe that you find this video lacking in details, but Tech Insight videos are actually supposed to be only high-level overview of technology - that's why this category resides in **Learn** section. As a general rule when talking about technical depth and detail, **Learn < Design < Build**. We are also trying to include information that can change in written articles (rather than videos), since those are much easier to update.
